// Code generated by protoc-gen-go. DO NOT EDIT.
// source: machine/service.proto

package machine

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Common metadata message nested in all reply message types
type NodeMetadata struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeMetadata) Reset()         { *m = NodeMetadata{} }
func (m *NodeMetadata) String() string { return proto.CompactTextString(m) }
func (*NodeMetadata) ProtoMessage()    {}
func (*NodeMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4ab5414893460c7, []int{0}
}

func (m *NodeMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMetadata.Unmarshal(m, b)
}
func (m *NodeMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMetadata.Marshal(b, m, deterministic)
}
func (m *NodeMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMetadata.Merge(m, src)
}
func (m *NodeMetadata) XXX_Size() int {
	return xxx_messageInfo_NodeMetadata.Size(m)
}
func (m *NodeMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMetadata proto.InternalMessageInfo

func (m *NodeMetadata) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type VersionResponse struct {
	Metadata             *NodeMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Version              *VersionInfo  `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Platform             *PlatformInfo `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4ab5414893460c7, []int{1}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetMetadata() *NodeMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *VersionResponse) GetVersion() *VersionInfo {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *VersionResponse) GetPlatform() *PlatformInfo {
	if m != nil {
		return m.Platform
	}
	return nil
}

type VersionReply struct {
	Response             []*VersionResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *VersionReply) Reset()         { *m = VersionReply{} }
func (m *VersionReply) String() string { return proto.CompactTextString(m) }
func (*VersionReply) ProtoMessage()    {}
func (*VersionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4ab5414893460c7, []int{2}
}

func (m *VersionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionReply.Unmarshal(m, b)
}
func (m *VersionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionReply.Marshal(b, m, deterministic)
}
func (m *VersionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionReply.Merge(m, src)
}
func (m *VersionReply) XXX_Size() int {
	return xxx_messageInfo_VersionReply.Size(m)
}
func (m *VersionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionReply.DiscardUnknown(m)
}

var xxx_messageInfo_VersionReply proto.InternalMessageInfo

func (m *VersionReply) GetResponse() []*VersionResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type VersionInfo struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Sha                  string   `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	Built                string   `protobuf:"bytes,3,opt,name=built,proto3" json:"built,omitempty"`
	GoVersion            string   `protobuf:"bytes,4,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	Os                   string   `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Arch                 string   `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionInfo) Reset()         { *m = VersionInfo{} }
func (m *VersionInfo) String() string { return proto.CompactTextString(m) }
func (*VersionInfo) ProtoMessage()    {}
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4ab5414893460c7, []int{3}
}

func (m *VersionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionInfo.Unmarshal(m, b)
}
func (m *VersionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionInfo.Marshal(b, m, deterministic)
}
func (m *VersionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionInfo.Merge(m, src)
}
func (m *VersionInfo) XXX_Size() int {
	return xxx_messageInfo_VersionInfo.Size(m)
}
func (m *VersionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VersionInfo proto.InternalMessageInfo

func (m *VersionInfo) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *VersionInfo) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

func (m *VersionInfo) GetBuilt() string {
	if m != nil {
		return m.Built
	}
	return ""
}

func (m *VersionInfo) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func (m *VersionInfo) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *VersionInfo) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

type PlatformInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode                 string   `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatformInfo) Reset()         { *m = PlatformInfo{} }
func (m *PlatformInfo) String() string { return proto.CompactTextString(m) }
func (*PlatformInfo) ProtoMessage()    {}
func (*PlatformInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4ab5414893460c7, []int{4}
}

func (m *PlatformInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformInfo.Unmarshal(m, b)
}
func (m *PlatformInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformInfo.Marshal(b, m, deterministic)
}
func (m *PlatformInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformInfo.Merge(m, src)
}
func (m *PlatformInfo) XXX_Size() int {
	return xxx_messageInfo_PlatformInfo.Size(m)
}
func (m *PlatformInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformInfo proto.InternalMessageInfo

func (m *PlatformInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlatformInfo) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeMetadata)(nil), "machine.NodeMetadata")
	proto.RegisterType((*VersionResponse)(nil), "machine.VersionResponse")
	proto.RegisterType((*VersionReply)(nil), "machine.VersionReply")
	proto.RegisterType((*VersionInfo)(nil), "machine.VersionInfo")
	proto.RegisterType((*PlatformInfo)(nil), "machine.PlatformInfo")
}

func init() { proto.RegisterFile("machine/service.proto", fileDescriptor_d4ab5414893460c7) }

var fileDescriptor_d4ab5414893460c7 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0xfd, 0x4a, 0x3b, 0x2d, 0x56, 0x96, 0x56, 0x42, 0x45, 0x94, 0x9c, 0xc4, 0x43, 0x8a,
	0x55, 0xc4, 0xab, 0x55, 0x0f, 0x1e, 0x2a, 0x25, 0x07, 0xaf, 0xb2, 0x4d, 0xb7, 0x49, 0x20, 0xc9,
	0x84, 0xec, 0xb6, 0xd0, 0xbf, 0xe0, 0x1f, 0xf1, 0x6f, 0xba, 0xd9, 0x6c, 0x96, 0x50, 0x6f, 0x2f,
	0x6f, 0xdf, 0xbc, 0x79, 0x33, 0x19, 0x98, 0xa6, 0x34, 0x88, 0xe2, 0x8c, 0xcd, 0x39, 0x2b, 0x0e,
	0x71, 0xc0, 0xbc, 0xbc, 0x40, 0x81, 0xc4, 0xd6, 0xf4, 0xec, 0x32, 0x44, 0x0c, 0x13, 0x36, 0x57,
	0xf4, 0x66, 0xbf, 0x9b, 0xb3, 0x34, 0x17, 0xc7, 0x4a, 0xe5, 0xde, 0xc1, 0xe8, 0x13, 0xb7, 0x6c,
	0xc5, 0x04, 0xdd, 0x52, 0x41, 0xc9, 0x0c, 0xfa, 0x11, 0x72, 0x91, 0xd1, 0x94, 0x39, 0xd6, 0x8d,
	0x75, 0x3b, 0xf0, 0xcd, 0xb7, 0xfb, 0x6b, 0xc1, 0xf8, 0x8b, 0x15, 0x3c, 0xc6, 0xcc, 0x67, 0x3c,
	0xc7, 0x8c, 0x33, 0x72, 0x0f, 0xfd, 0x54, 0xd7, 0x2a, 0xfd, 0x70, 0x31, 0xf5, 0x74, 0x63, 0xaf,
	0x69, 0xec, 0x1b, 0x19, 0xf1, 0xc0, 0x3e, 0x54, 0x2e, 0x4e, 0x4b, 0x55, 0x4c, 0x4c, 0x85, 0x76,
	0xff, 0xc8, 0x76, 0xe8, 0xd7, 0xa2, 0xb2, 0x45, 0x9e, 0x50, 0xb1, 0xc3, 0x22, 0x75, 0xda, 0x27,
	0x2d, 0xd6, 0xfa, 0x41, 0x55, 0x18, 0x99, 0xfb, 0x06, 0x23, 0x13, 0x34, 0x4f, 0x8e, 0xe4, 0x11,
	0xfa, 0x85, 0x4e, 0x2c, 0x53, 0xb6, 0xa5, 0x85, 0x73, 0xda, 0xb3, 0x9e, 0xc8, 0x37, 0x4a, 0xf7,
	0xc7, 0x82, 0x61, 0x23, 0x11, 0x39, 0x87, 0xb6, 0xa0, 0xa1, 0x5e, 0x4b, 0x09, 0x4b, 0x86, 0x47,
	0x54, 0x8d, 0x21, 0x19, 0x09, 0xc9, 0x04, 0xba, 0x9b, 0x7d, 0x9c, 0x08, 0x95, 0x74, 0xe0, 0x57,
	0x1f, 0xe4, 0x0a, 0x20, 0xc4, 0xef, 0x7a, 0xea, 0x8e, 0x7a, 0x1a, 0x84, 0xa8, 0xcd, 0xc9, 0x19,
	0xb4, 0x90, 0x3b, 0x5d, 0x45, 0x4b, 0x44, 0x08, 0x74, 0x68, 0x11, 0x44, 0x4e, 0x4f, 0x31, 0x0a,
	0xbb, 0x4f, 0x30, 0x6a, 0x0e, 0x5b, 0x6a, 0x1a, 0x3f, 0x49, 0xe1, 0x92, 0x4b, 0xe5, 0xce, 0x75,
	0x1e, 0x85, 0x17, 0xaf, 0x60, 0xaf, 0xaa, 0x49, 0xc9, 0x33, 0xd8, 0x75, 0xc7, 0x0b, 0xaf, 0x3a,
	0x0a, 0xaf, 0x3e, 0x0a, 0xef, 0xbd, 0x3c, 0x8a, 0xd9, 0xf4, 0xff, 0x5a, 0xe4, 0xfe, 0x96, 0xd7,
	0x30, 0x0e, 0x30, 0x35, 0x6f, 0x34, 0x8f, 0x97, 0xa0, 0x5d, 0x5f, 0xf2, 0x78, 0x6d, 0x6d, 0x7a,
	0xca, 0xe7, 0xe1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x70, 0x5e, 0x42, 0x8c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MachineClient is the client API for Machine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MachineClient interface {
	Version(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionReply, error)
}

type machineClient struct {
	cc *grpc.ClientConn
}

func NewMachineClient(cc *grpc.ClientConn) MachineClient {
	return &machineClient{cc}
}

func (c *machineClient) Version(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionReply, error) {
	out := new(VersionReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineServer is the server API for Machine service.
type MachineServer interface {
	Version(context.Context, *empty.Empty) (*VersionReply, error)
}

// UnimplementedMachineServer can be embedded to have forward compatible implementations.
type UnimplementedMachineServer struct {
}

func (*UnimplementedMachineServer) Version(ctx context.Context, req *empty.Empty) (*VersionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}

func RegisterMachineServer(s *grpc.Server, srv MachineServer) {
	s.RegisterService(&_Machine_serviceDesc, srv)
}

func _Machine_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).Version(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Machine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "machine.Machine",
	HandlerType: (*MachineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Machine_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "machine/service.proto",
}
